### ISSUE TITLE
Add triqs support

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#89]
Maybe we can wrap the one and two electron integrals, so it's supported by triqs. Specifically, we can interface to this function: https://triqs.github.io/triqs/latest/documentation/python_api/triqs.operators.util.hamiltonians.h_int_slater.html#triqs.operators.util.hamiltonians.h_int_slater

One way of doing it is wrapping 1 electron integral into the two electron integrals, using outer product:

$$V_{I, j, k, l} = \hat{h} \otimes I + I \otimes \hat{h} + v_{i,j,k,l}$$

**Comment by PaulWAyers** [comment]
This is the "reduced Hamiltonian." You may need to also know the number of electrons. See 1.3, 1.13, and 1.14 in [Ward Poelman's thesis, for example](https://biblio.ugent.be/publication/6933577).

**Comment by adsrichards** [comment]
@RichRick1 You may also want to be careful with how the interaction hamiltonian is defined/interpreted in TRIQS. This is meant to be the local interacting part of an impurity hamiltonian. You can see the typical definition on the [cthyb](https://triqs.github.io/cthyb/latest/) page. The intersite hopping for the non-interacting model would enter into the first term, and it looks like you can set a one-body term for the local set of correlated orbitals by using the [h_loc0](https://triqs.github.io/cthyb/latest/_ref/triqs_cthyb.solver.Solver.h_loc0.html#triqs_cthyb.solver.Solver.h_loc0) parameter in cthyb.

**Comment by PaulWAyers** [comment]
The impurity Hamiltonian here has exactly the right form. I would assume(?) that triqs is clever enough to realize that an impurity with no bath is just an isolated system? Or, equivalently one could just set $V_{k \alpha} = 0$ as a bath decoupled to an impurity just gives a product wavefunction.

**Comment by adsrichards** [comment]
@PaulWAyers I definitely agree that this should be possible in TRIQS. One could also just ignore the bath and work with the local/impurity hamiltonian. I am just a bit concerned about how useful this would be within TRIQS though. Since TRIQS is primarily a DMFT library, users of TRIQS may want to keep one-body and two-body terms separate. Although, I am more familiar with setting up the hamiltonian for DFT+DMFT calculations where the two-body term typically consists of a set of d or f orbitals on a single atom, and the non-interacting hamiltonian is obtained from DFT. I can say that I have found it useful to work with the one-body term when setting up coherent-potential-approximation calculations in TRIQS, and it may be useful to manipulate this term in the cellular extension of DMFT which I am less familiar with.
